---
name: "Cleanup the repo every two weeks"
on:
  schedule:
  - cron: "0 5 1,15 * *"
jobs:
  clean:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install git -y
      - name: Cleanup the repo
        run: |
          git clone https://github.com/kubeinit-bot/kubeinit-ci-results.git --branch main --single-branch
          cd kubeinit-ci-results
          ls | grep -v periodic | grep -v index | grep -v README |
              while read line; do
              rm -rf $line
          done
          git config --global init.defaultBranch main
          git config --global user.email "bot@kubeinit.com"
          git config --global user.name "KubeInit's bot"         
          rm -rf .git
          git init
          git remote add origin https://github.com/kubeinit-bot/kubeinit-ci-results.git
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kubeinit-bot/kubeinit-ci-results.git
          git add .
          git commit -m "Initial clean commit"
          git push origin main --force
